# 1) N-D array

- N-dimezionalne pole, s n-poctom dimenzii, v ktorych je usporiadane pole
- pr. 2D pole predstavuje tabulku s riadkami (rows) a stlpcami (columns)
- pr. 3D pole predstavuje kocku s vyskou, sit=rkou a hlbkou 


## 1.1) N-D array creation

- **np.array()** - pole vytvorene z listu
- **np.zeros()** - pole vyplnene len nulami 0
- **np.ones()** - pole vyplnene len jednotkami 1
- **np.arange()** - vrati pole s hodnotami v definovanom intervale
- **np.full()** - pole so specifickou hodnotou
- **np.random.rand()** - pole s nahodnymi hodnotami
- **np.empty()** - prazdne pole

### 1.1.1) N-D creation from list of lists

In [ ]:
import numpy as np

# 2D pole s 2 riadkami a 4 stlpcami
arr2D = np.array([[1, 2, 3, 4], [5, 6, 4, 8]])

print("2D\n", arr2D, "\n")

# 3D pole s 2 "platkami (slices)", kazdy slice ma 3 riadky a 4 stlpcami
arr3D = np.array(
    [
        [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
        [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]],
    ]
)

print("3D\n", arr3D, "\n")

2D
 [[1 2 3 4]
 [5 6 4 8]] 

3D
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]] 



### 1.1.2) N-D creation using np.zeros()

In [ ]:
import numpy as np

# 2D pole s 2 riadkami a 3 stlpcami vyplnene 0
arr2D = np.zeros((2, 3))
print("2D\n", arr2D, "\n")

# 3D pole rozmerov 2x3x4 vyplnene 0
arr3D = np.zeros((2, 3, 4))
print("3D\n", arr3D, "\n")

2D
 [[0. 0. 0.]
 [0. 0. 0.]] 

3D
 [[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]] 



### 1.1.3) N-D creation using np.full()

In [ ]:
import numpy as np

# 2D pole rozmer 2x2 vyplnene 5
arr2D = np.full((2, 2), 5)
print("2D\n", arr2D)

2D
 [[5 5]
 [5 5]]


### 1.1.3) N-D creation using np.random.rand()

In [ ]:
import numpy as np

# 2D pole 2x2 s nahodnymi cislami
arr2D = np.random.rand(2, 2)
print("2D\n", arr2D)

# 3D pole 2x2x2 s nahodnymi cislami
arr3D = np.random.rand(3, 2, 2)
print("3D\n", arr3D)

2D
 [[0.97072004 0.19545232]
 [0.22599203 0.89164101]]
3D
 [[[0.27895543 0.69472073]
  [0.59456776 0.9892985 ]]

 [[0.05008949 0.99509182]
  [0.5129192  0.84571791]]

 [[0.1828345  0.62003761]
  [0.61414128 0.65299364]]]


### 1.1.4) N-D empty

In [ ]:
import numpy as np

# 2D prazdne pole 2x2
arr2D = np.empty((2, 2))
print(f"2D\n {arr2D}\n")

# 3D prazdne pole 3x2x2
arr3D = np.empty((3, 2, 2))
print(f"3D\n {arr3D}\n")

2D
 [[0.97072004 0.19545232]
 [0.22599203 0.89164101]]

3D
 [[[0.27895543 0.69472073]
  [0.59456776 0.9892985 ]]

 [[0.05008949 0.99509182]
  [0.5129192  0.84571791]]

 [[0.1828345  0.62003761]
  [0.61414128 0.65299364]]]

