# 1) Numpy data types

1. **int8, int16, int32, int64** - signed integer types with different bit sizes
2. **uint8, uint16, uint32, uint64** - unsigned integer types with different bit sizes
3. **float32, float64** - floating-point types with different precision levels
4. **complex64, complex128** - complex number types with different precision levels

## 1.1) Check data type

- **.dtype**

In [ ]:
import numpy as np

# pole z listu
arr = np.array([1, 2, 3])

print(arr.dtype)
print(type(arr))

int64
<class 'numpy.ndarray'>


In [ ]:
import numpy as np

# pole z integers
arr_int = np.array([-1, 3, 6, 5])

# pole z float
arr_float = np.array([0.1, 0.2, 0.3])

# pole z komplexnych cisel
arr_complex = np.array([1 + 2j, 2 + 3j, 3 + 4j])

# zobrazenie typov
print("Integer:", arr_int.dtype)
print("Float:", arr_float.dtype)
print("Complex:", arr_complex.dtype)

Integer: int64
Float: float64
Complex: complex128


## 1.2) Creating array with defined data type

In [ ]:
import numpy as np

# pole s 32-bit integer
arr = np.array([1, 3, 7], dtype="int32")

print(arr, arr.dtype)

[1 3 7] int32


In [ ]:
import numpy as np

# pole 8-bit integers
arr8bit = np.array([1, 3, 7], dtype="int8")

# pole s unsigned 16-bit integers
arr16bit = np.array([1, 3, 7], dtype="uint16")

# pole 32-bit floating
arr32float = np.array([0.1, 1.3, 2.4], dtype="float32")

# pole 64-bit komplexne cisla
arr64complex = np.array([1 + 2j, 2 + 3j, 3 + 4j], dtype="complex64")

# zobrazenie
print("Int 8-bit:", arr8bit, arr8bit.dtype)
print("Int 16-bit:", arr16bit, arr16bit.dtype)
print("Float 32-bit:", arr32float, arr32float.dtype)
print("Complex 64-bit:", arr64complex, arr64complex.dtype)

Int 8-bit: [1 3 7] int8
Int 16-bit: [1 3 7] uint16
Float 32-bit: [0.1 1.3 2.4] float32
Complex 64-bit: [1.+2.j 2.+3.j 3.+4.j] complex64


## 1.3) Type conversion

- **astype()** - method

In [ ]:
import numpy as np

# pole integers
arr = np.array([1, 2, 3, 4])

# convert to float
arr_float = arr.astype("float")

# zobrazenie
print(arr, arr.dtype)
print(arr_float, arr_float.dtype)

[1 2 3 4] int64
[1. 2. 3. 4.] float64
