# 1) Numpy array slicing

- **slicing (krajanie)** - proces extrakcie casti pola
- syntax: `array[start:stop:step]`

# 2) 1D array slicing

In [ ]:
import numpy as np

# 1D array
arr = np.array([1, 3, 5, 7, 8, 9, 2, 4, 6])
print("Array", arr)

# slice from index 2 to index 6 (exclusive)
print("Slice from index 2-6:", arr[2:6])

# slice from index 0 to index 8 (exclusive) with a step size of 2
print("Slice from 0-8, step 2:", arr[0:8:2])

# slice from index 3 up to the last element
print("Slice from 3-last:", arr[3:])

# items from start to end
print("Items from start-end:", arr[:])

Array [1 3 5 7 8 9 2 4 6]
Slice from index 2-6: [5 7 8 9]
Slice from 0-8, step 2: [1 5 8 2]
Slice from 3-last: [7 8 9 2 4 6]
Items from start-end: [1 3 5 7 8 9 2 4 6]


# 3) Modify array elements using slicing

- modify using:
    - **start**
    - **stop**
    - **start** and **stop**
    - **start**, **stop** and **step**

In [ ]:
import numpy as np

# 1D array
arr = np.array([2, 4, 6, 8, 10, 12])
print("Array", arr)

# start parameter
# modify elements from index 3 onwards
arr[3:] = 20
print("Modified from 3 index:", arr)

# stop parameter
# modify the first 3 elements
arr[:3] = 1
print("Modified first 3 elements:", arr)

# start, stop parameters
# modify elements from indices 2 to 5
arr[2:5] = 40
print("Modified from 2-5 elements", arr)

# start, stop, step parameters
# modify every second element from indices 1 to 5
arr[1:5:2] = 100
print("Modified every second from 1-5 elements", arr)

Array [ 2  4  6  8 10 12]
Modified from 3 index: [ 2  4  6 20 20 20]
Modified first 3 elements: [ 1  1  1 20 20 20]
Modified from 2-5 elements [ 1  1 40 40 40 20]
Modified every second from 1-5 elements [  1 100  40 100  40  20]


# 4) Negative slicing

- elemty pocitame od konca pola

In [ ]:
import numpy as np

# 1D array
arr = np.array([2, 4, 6, 8, 10, 12])

# slice the last 3 elements of the array
# using the start parameter
print("Slice last 3 elements:", arr[-3:])

# slice elements from 2nd-to-last to 4th-to-last element
# using the start and stop parameters
print("Slice from 2nd-to-last to 4th-to-last element:", arr[-5:-2])

# slice every other element of the array from the end
# using the start, stop, and step parameters
print("Slice every other element from the end:", arr[-1::-2])

Slice last 3 elements: [ 8 10 12]
Slice from 2nd-to-last to 4th-to-last element: [4 6 8]
Slice every other element from the end: [12  8  4]


# 5) Reverse array using negative slicing

In [ ]:
import numpy as np

# 1D pole
arr = np.array([2, 4, 6, 8, 10, 12])
print("Array", arr)

# reverse array using slicing
print("reverse using slicing", arr[::-1])

Array [ 2  4  6  8 10 12]
reverse using slicing [12 10  8  6  4  2]


# 6) 2D numpy array slicing

- musime specifikovat pre kazdu dimenziu pola, cize pre riadky a stlpce
- syntax: `array[row_start:row_stop:row_step, col_start:col_stop:col_step]`

In [ ]:
import numpy as np

# 2D pole
arr = np.array([[1, 3, 5, 7], [9, 11, 13, 15], [2, 4, 6, 8]])
print("Array\n", arr)

# slice the array to get the first two rows and columns
print("Array first 2 rows and columns\n", arr[0:2, 0:2])

# slice the array to get the last two rows and columns
print("Array last 2 rows and columns\n", arr[-2:, -2:])

Array
 [[ 1  3  5  7]
 [ 9 11 13 15]
 [ 2  4  6  8]]
Array first 2 rows and columns
 [[ 1  3]
 [ 9 11]]
Array last 2 rows and columns
 [[13 15]
 [ 6  8]]
