# 1) Numpy array reshaping

- zmena tvaru/shape pola bez zmeny udajov
- zmena napr. 1D pola na N-d(2D) pole
- syntax: `np.reshape(array, newshape, order = 'C')`
    - array - vstupne pole
    - newshape - pozadovany tvar pola
    - order (optional) - urcuje poradie v ktorom prvky pola maju byt usporiadane. Defaultne je nastavene 'C'
    - pozn.: order moze byt: 'C', 'F', 'A'

# 2) Reshape 1D array to 2D array

- definujem pocet riadkov a stlpcov

In [ ]:
import numpy as np

# 1D pole
arr = np.array([1, 3, 5, 7, 2, 4, 6, 8])
print("1D array\n", arr)

# reshape a 1D array into a 2D array
# with 2 rows and 4 columns
# newshape dafinujem pomocou tuple (2-riadky,4-stlpce)
arr2D = np.reshape(arr, (2, 4))
print("Reshaped 2D array\n", arr2D)

# reshape a 1D array into a 2D array with a single row
arr2D_single_row = np.reshape(arr, (1, 8))
print("Reshaped 2D single row array\n", arr2D_single_row)

1D array
 [1 3 5 7 2 4 6 8]
Reshaped 2D array
 [[1 3 5 7]
 [2 4 6 8]]
Reshaped 2D single row array
 [[1 3 5 7 2 4 6 8]]


# 3) reshape 1D array to 3D array

- definujem pocet riadkov, stlpcov a vrstiev

In [ ]:
import numpy as np

# 1D pole
arr = np.array([1, 3, 5, 7, 2, 4, 6, 8])
print("Array\n", arr)

# reshape 1D to 3D array
arr3D = np.reshape(arr, (2, 2, 2))
print("Reshaped 3D array\n", arr3D)

Array
 [1 3 5 7 2 4 6 8]
Reshaped 3D array
 [[[1 3]
  [5 7]]

 [[2 4]
  [6 8]]]


# 4) Flatten (splostit) N-d array to 1D using reshape()

- konvertujem multidimenzionalne pole do 1D pola
- **-1** - ako "newshape" argument vo f-cie reshape() 

In [ ]:
import numpy as np

# flatten 2D array to 1D
arr2D = np.array([[1, 3], [5, 7], [9, 11]])
print("2D array\n", arr2D)

arr1D = np.reshape(arr2D, -1)
print("Flattened 1D array\n", arr1D)

# flatten 3D array to 1D
arr3D = np.array([[[1, 3], [5, 7]], [[2, 4], [6, 8]]])
print("\n3D array\n", arr3D)

arr1D = np.reshape(arr3D, -1)
print("Flattened 1D array\n", arr1D)

2D array
 [[ 1  3]
 [ 5  7]
 [ 9 11]]
Flattened 1D array
 [ 1  3  5  7  9 11]

3D array
 [[[1 3]
  [5 7]]

 [[2 4]
  [6 8]]]
Flattened 1D array
 [1 3 5 7 2 4 6 8]
