# 1) Numpy array functions

- array functions:

|Array Operations                   |Functions|
|---                                |---|    
|Array Creation Functions           |np.array(), np.zeros(), np.ones(), np.empty(), etc.|
|Array Manipulation Functions       |np.reshape(), np.transpose(), etc.|
|Array Mathematical Functions       |np.add(), np.subtract(), np.sqrt(), np.power(), etc.|
|Array Statistical Functions        |np.median(), np.mean(), np.std(), and np.var().|
|Array Input and Output Functions   |np.save(), np.load(), np.loadtxt(), etc.|

## 1.1) Creation functions

In [ ]:
import numpy as np

# create an array using np.array()
arr = np.array([1, 3, 5])
print(arr)

# create an array filled with zeros using np.zeros()
arr_zero = np.zeros((2, 2))
print(arr_zero)

# create an array filled with ones using np.ones()
arr_one = np.ones((2, 4))
print(arr_one)

[1 3 5]
[[0. 0.]
 [0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## 1.2) Manipulation functions

In [ ]:
import numpy as np

# 1D array
arr = np.array([1, 3, 5, 7, 9, 11])
print("Arr1D:\n", arr)

# reshape the 1D array into a 2D array
arr2D = np.reshape(arr, (2, 3))
print("\nArr2D:\n", arr2D)

# transpose the 2D array
arr_transpose = np.transpose(arr2D)
print("\nArr transposed:\n", arr_transpose)

Arr1D:
 [ 1  3  5  7  9 11]

Arr2D:
 [[ 1  3  5]
 [ 7  9 11]]

Arr transposed:
 [[ 1  7]
 [ 3  9]
 [ 5 11]]


## 1.3) Mathematical functions

In [ ]:
import numpy as np

# create two arrays
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([4, 9, 16, 25, 36])

# add the two arrays element-wise
arr_sum = np.add(arr1, arr2)

# subtract the array2 from array1 element-wise
arr_diff = np.subtract(arr1, arr2)

# compute square root of array2 element-wise
# arr_sqrt=np.power(arr2,0.5)
arr_sqrt = np.sqrt(arr2)


print("\nSum of arrays:\n", arr_sum)
print("\nDifference of arrays:\n", arr_diff)
print("\nSquare root of second array:\n", arr_sqrt)


Sum of arrays:
 [ 5 11 19 29 41]

Difference of arrays:
 [ -3  -7 -13 -21 -31]

Square root of second array:
 [2. 3. 4. 5. 6.]


## 1.4) Statistical functions

In [ ]:
import numpy as np

# create a numpy array
marks = np.array([76, 78, 81, 66, 85])

# compute the mean of marks
mean_marks = np.mean(marks)
print("Mean:", mean_marks)

# compute the median of marks
median_marks = np.median(marks)
print("Median:", median_marks)

# find the minimum and maximum marks
min_marks = np.min(marks)
print("Minimum marks:", min_marks)

max_marks = np.max(marks)
print("Maximum marks:", max_marks)

Mean: 77.2
Median: 78.0
Minimum marks: 66
Maximum marks: 85


## 1.5) Input/Outpu (I/O) functions

In [ ]:
import numpy as np

# create an array
arr = np.array([[1, 3, 5], [2, 4, 6]])

# save the array to a text file
# np.savetxt('data.txt', arr)

# load the data from the text file
# loaded_data = np.loadtxt('arr.txt')

# print the loaded data
# print(loaded_data)