# 1) Numpy comparison/logical operations

## 1.1) Comparison operators

|Operators                      |Descriptions|
|---|---|
|< (less than)	                |returns True if element of the first array is less than the second one|
|<= (less than or equal to)	    |returns True if element of the first array is less than or equal to the second one|
|> (greater than)	            |returns True if element of the first array is greater than the second one|
|>= (greater than or equal to)  |returns True if element of the first array is greater than or equal to the second one|
|== (equal to)	                |returns True if the element of the first array is equal to the second one|
|!= (not equal to)	            |returns True if the element of the first array is not equal to the second one|

In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([3, 2, 1])

print("arr1:\n", arr1, "\narr2:\n", arr2)

# less than operator
result1 = arr1 < arr2
print("arr1 < arr2:", result1)

# greater than operator
result2 = arr1 > arr2
print("arr1 > arr2:", result2)

# equal to operator
result3 = arr1 == arr2
print("arr1 == arr2:", result3)

arr1:
 [1 2 3] 
arr2:
 [3 2 1]
arr1 < arr2: [ True False False]
arr1 > arr2: [False False  True]
arr1 == arr2: [False  True False]


## 1.2) Comparison functions

|Functions	        |Descriptions|
|---|---|
|less()	            |returns element-wise True if the first value is less than the second|
|less_equal()       |returns element-wise True if the first value is less than or equal to second|
|greater()          |returns element-wise True if the first value is greater then second|
|greater_equal()    |returns element-wise True if the first value is greater than or equal to second|
|equal()            |returns element-wise True if two values are equal|
|not_equal()        |returns element-wise True if two values are not equal|

In [ ]:
import numpy as np

arr1 = np.array([9, 12, 21])
arr2 = np.array([21, 12, 9])

print("arr1:\n", arr1, "\narr2:\n", arr2)

# use of less()
result = np.less(arr1, arr2)
print("Using less():", result)

# use of less_equal()
result = np.less_equal(arr1, arr2)
print("Using less_equal():", result)

# use of greater()
result = np.greater(arr1, arr2)
print("Using greater():", result)

# use of greater_equal()
result = np.greater_equal(arr1, arr2)
print("Using greater_equal():", result)

# use of equal()
result = np.equal(arr1, arr2)
print("Using equal():", result)

# use of not_equal()
result = np.not_equal(arr1, arr2)
print("Using not_equal():", result)

arr1:
 [ 9 12 21] 
arr2:
 [21 12  9]
Using less(): [ True False False]
Using less_equal(): [ True  True False]
Using greater(): [False False  True]
Using greater_equal(): [False  True  True]
Using equal(): [False  True False]
Using not_equal(): [ True False  True]


## 1.3) Logical operations

|Operators	    |Descriptions|
|---|---|
|logical_and    |Computes the element-wise truth value of x1 AND x2|
|logical_or	    |Computes the element-wise truth value of x1 OR x2|
|logical_not	|Computes the element-wise truth value of NOT x|

In [ ]:
import numpy as np

x1 = np.array([True, False, True])
x2 = np.array([False, False, True])

print("arr1:\n", x1, "\narr2:\n", x2, "\n")

# Logical AND
print("Logical AND:", np.logical_and(x1, x2))

# Logical OR
print("Logical OR:", np.logical_or(x1, x2))

# Logical NOT
print("Logical NOT:", np.logical_not(x1))

arr1:
 [ True False  True] 
arr2:
 [False False  True] 

Logical AND: [False False  True]
Logical OR: [ True False  True]
Logical NOT: [False  True False]
