# 1) Numpy broadcasting

- **broadcasting** - ak vykonavame matematicke operacie s poliami roznych tvarov, npar. 1D s 2D, tak pole 1D sa rozsiri na velkost 2D.
- funguje iba na kompatibilnych poliach, numpy porovnava sadu poli zprava dolava.
- sada dlzok poli je kompatibilna ak:
    - jedno z poli ma dlzku **1**, alebo
    - su totozne/rovnake
    - pr. kompatibility: (6,7) a (6,7); (6,1) a (6,7); (6,7) a (7, ) - pretoze najviac vpravo rozmery su oba 7???
    - pr. nekompatibility: (6,7) a (7,6); (6,7) a (7, )

In [1]:
import numpy as np

# create 1-D array
arr1D = np.array([1, 2, 3])

# create 2-D array
arr2D = np.array([[1], [2], [3]])

# add arrays of different dimension
# size of array1 expands to match with array2
sum = arr1D + arr2D

print(sum)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


## 1.1) Broadcasting with scalars (single value)

In [2]:
import numpy as np

# 1-D array
arr1D = np.array([1, 2, 3])

# scalar
number = 5

# add scalar and 1-D array
sum = np.add(arr1D, number)

print(sum)

[6 7 8]
