# 1) Numpy vectorization

- umoznuje matematicke operacie v celom poli bez nutnosti 'loop' prechadzania jednotlivych prvkov
- numpy vektorizacia je zalozena na C jazyku, pretoze je ovela efektivnejsi ako python jazyk
- **v podstate for loop pre numpy**

In [ ]:
# Numpy Vectorization to Add Two Arrays Together
import numpy as np

# define two 2D arrays
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[0, 1, 2], [0, 1, 2]])

print("Array 1:\n", arr1)
print("Array 2:\n", arr2)

# add two arrays (vectorization)
print("Sum between two arrays:\n", np.add(arr1, arr2))

Array 1:
 [[1 2 3]
 [4 5 6]]
Array 2:
 [[0 1 2]
 [0 1 2]]
Sum between two arrays:
 [[1 3 5]
 [4 6 8]]


## 1.!) Numpy vectorization vs python for loop

In [2]:
# Python for loop
import time

start = time.time()

array1 = [1, 2, 3, 4, 5]

for i in range(len(array1)):
    array1[i] += 10

end = time.time()

print("For loop time:", end - start)

For loop time: 0.0001857280731201172


In [ ]:
# NumPy Vectorization
import numpy as np
import time

start = time.time()

array1 = np.array([1, 2, 3, 4, 5])

result = array1 + 10

end = time.time()

print("Vectorization time:", end - start)

Vectorization time: 0.0002002716064453125


## 1.2) Vectorize()

- v numpy je kazda matematicka operacia vektorizovana

In [ ]:
import numpy as np

# array
arr = np.array([-1, 0, 2, 3, 4])


# function that returns the square of positive numbers
def find_square(x):
    if x < 0:
        return 0
    else:
        return x**2


# vectorize() to vectorize the function find_square
vectorized_function = np.vectorize(find_square)

# passing an array to a vectorized function
result = vectorized_function(arr)

print(result)

[ 0  0  4  9 16]
