# 1) Numpy boolean indexing

- umoznuje filtrovat hodnoty na zaklade urcitej podmienky
- pouzivame boolean mask

## 1.1) Boolean mask

- boolean mask - je numpy pole obsahujuce hodnoty True/False

In [ ]:
import numpy as np

arr = np.array([12, 24, 16, 21, 32, 29, 7, 15])

# boolean mask, ktora vyhodnoti prvky vacsie ako 20, ako True
boolean_mask = arr > 20

print(boolean_mask)

[False  True False  True  True  True False False]


## 1.2) 1D boolean indexing

- boolean mask umoznuje vytvorit filter, ktory pouzijeme ako index pre numpy pole
- boolean mask oznaci iba tie prvky v poli, ktore maju True hodnotu

In [ ]:
# Boolean indexing na selekciu neparnych cisel
import numpy as np

# 1D array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Array:", arr)

# vytvorenie podmienky pre selekciu neparnych cisel
boolean_mask = arr % 2 != 0

# pouzitie boolean mask ako boolean indexing filtra
odd_numbers = arr[boolean_mask]
print("Odd (neparne) cisla z arr:", odd_numbers)

Array: [ 1  2  3  4  5  6  7  8  9 10]
Odd (neparne) cisla z arr: [1 3 5 7 9]


In [ ]:
# create a boolean mask using combined logical operators
import numpy as np

arr = np.array([1, 2, 4, 9, 11, 16, 18, 22, 26, 31, 33, 47, 51, 52])
print("Array", arr)

# vytvorenie boolean mask pre kombinaciu podmienok
boolean_mask = (arr < 10) | (arr > 40)

# aplikacia boolean mask ako filtra
results = arr[boolean_mask]
print("Result:", results)

Array [ 1  2  4  9 11 16 18 22 26 31 33 47 51 52]
Result: [ 1  2  4  9 47 51 52]


## 1.3) Modify elements using boolean indexing

In [ ]:
# change all even numbers to 0 in the copy
import numpy as np

# 1D array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Array", arr)

# copy array
arr_copy = arr.copy()

# boolen indexing condition
boolean_mask = arr_copy % 2 == 0

# replace all even numbers as 0
arr_copy[boolean_mask] = 0
print("Even no. replaced by 0:", arr_copy)

Array [ 1  2  3  4  5  6  7  8  9 10]
Even no. replaced by 0: [1 0 3 0 5 0 7 0 9 0]


## 1.4) 2D boolean indexing

In [ ]:
import numpy as np

# 2D array 3x3
arr = np.array([[1, 7, 9], [14, 19, 21], [25, 29, 35]])
print("2D array\n", arr)

# boolen mask condition elements > 9
boolean_mask = arr > 9

# aplikacia boolean mask ako filtra
result = arr[boolean_mask]
print("Elements greater than 9:", result)

2D array
 [[ 1  7  9]
 [14 19 21]
 [25 29 35]]
Elements greater than 9: [14 19 21 25 29 35]
