# 1) Numpy fancy indexing

- umoznuje pouzit pole indexov na pristup k viacerym prvkom pola naraz
- umoznuje vykonat pokrocilejsie operacie s polom, napr:
    - conditional filtering
    - sorting a pod.

## 1.1) Select multiple elements using fancy indexing

In [ ]:
import numpy as np

# 1D array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print("Array", arr)

# select single element
select_single = arr[3]
print("Selected single element:", select_single)

# select elements at index 1,2,5,7
select_elements = arr[[1, 2, 5, 7]]
print("Selected elements:", select_elements)

Array [1 2 3 4 5 6 7 8]
Selected single element: 4
Selected elements: [2 3 6 8]


## 1.2) Fancy indexing for sorting array

- syntax: `array[np.argsort(array)]`
- for "descending order" pouzijem **-** pre argument f-cie argsort(), np.argsort(-array)

In [ ]:
import numpy as np

arr = np.array([3, 2, 6, 1, 8, 5, 7, 4])
print("Array", arr)

# sort array using fancy indeexing
sorted_arr = arr[np.argsort(arr)]
print("Sorted array:", sorted_arr)

Array [3 2 6 1 8 5 7 4]
Sorted array: [1 2 3 4 5 6 7 8]


In [ ]:
# descending order sort
import numpy as np

arr = np.array([3, 2, 6, 1, 8, 5, 7, 4])
print("Array", arr)

# sort array using fancy indeexing
sorted_arr = arr[np.argsort(-arr)]
print("Sorted array:", sorted_arr)

Array [3 2 6 1 8 5 7 4]
Sorted array: [8 7 6 5 4 3 2 1]


## 1.3) Fancy indexing to assing new value to specific elements

In [ ]:
import numpy as np

# 1D array
arr = np.array([3, 2, 6, 1, 8, 5, 7, 4])
print("Array", arr)

# vytvorim list indexov prvkov pre ktore chcem menit hodnotu
list_idx = [1, 3, 6]

# vytvorim list novych hodnot
new_values = [10, 20, 30]

# fancy indexing na priradenie novych hodnot pre dane elemnty
arr[list_idx] = new_values
print("New values array", arr)

Array [3 2 6 1 8 5 7 4]
New values array [ 3 10  6 20  8  5 30  4]


## 1.4) Fancy indexing on N-d arrays

In [ ]:
import numpy as np

# 2D array 3x3
arr = np.array([[1, 3, 5], [11, 7, 9], [13, 18, 29]])
print("2D array\n", arr)

# create an array of row indices
row_indices = np.array([0, 2])

# use fancy indexing to select specific rows
selected_rows = arr[row_indices]

print("\nSelected rows\n", selected_rows)

2D array
 [[ 1  3  5]
 [11  7  9]
 [13 18 29]]

Selected rows
 [[ 1  3  5]
 [13 18 29]]
