# 1) Numpy random

- **random** module - obsahuje f-cie, napr. **randit()** na generovanie nahodnych cisel

## 1.1) Generate random integer

- **random.randit()**

In [1]:
import numpy as np

# generate random integer from 0 to 9
random_number = np.random.randint(0, 10)

print(random_number)

6


## 1.2) Generate random float

- **random.rand()**

In [2]:
import numpy as np

# generate random float-point number between 0 and 1
random_number = np.random.rand()

print(random_number)

0.2838709399971098


## 1.3) Generate random array

In [ ]:
import numpy as np

# generate 1D array of 5 random integers between 0 and 9
arr_int = np.random.randint(0, 10, 5)
print("Random integer array:", arr_int)

# generate 1D array of 5 random numbers between 0 and 1
arr_float = np.random.rand(5)
print("Random float array:", arr_float)

# generate 2D array of shape (3, 4) with random integers
arr2D = np.random.randint(0, 10, (3, 4))
print("Random 2D array:\n", arr2D)

Random integer array: [5 4 4 8 8]
Random float array: [0.4353485  0.22415789 0.92648029 0.57665225 0.6612046 ]
Random 2D array:
 [[5 6 7 8]
 [4 2 1 3]
 [4 0 1 0]]


## 1.4) Choose random number from array

- **random.choice()**

In [ ]:
import numpy as np

# 1D array
arr = np.array([1, 2, 3, 4, 5])
print("Array:", arr)

# choose a random number from array
random_number = np.random.choice(arr)
print("Random number from array:", random_number)

Array: [1 2 3 4 5]
Random number from array: 2
