# 1) Numpy linear algebra

- linear algebra functions:

|Operators	|Descriptions|
|---        |---|
|dot()	    |calculates product (sucin) of two arrays|
|inner()	|calculates inner product of arrays|
|outer()	|calculates outer product of arrays|
|linalg.det()	    |calculates determinant of a matrix|
|linalg.solve()	|solves linear matrix equation|
|linalg.inv()	    |calculates the multiplicative inverse of the matrix|
|trace()	|calculates the sum of diagonal elements|

## 1.1) dot() - multiplication

In [ ]:
import numpy as np

arr1 = np.array([1, 3, 5])
arr2 = np.array([2, 4, 6])

# use of dot() to perform array multiplication
result = np.dot(arr1, arr2)

print(result)
# output: 44
# 1*2 + 3*4 + 5*6 = 44

44


## 1.2) inner()

- vypocet vnutornych sucinov 2 poli, ktory je suctom sucinov ich zodpovedajucich prvkov

In [ ]:
import numpy as np

arr1 = np.array([[1, 3], [5, 7]])
arr2 = np.array([[2, 4], [6, 8]])

# inner() for 2D arrays
result = np.inner(arr1, arr2)

print(result)

# output calc
# 1*2+3*4  1*6+3*8
# 5*2+7*4  5*6+7*8

[[14 30]
 [38 86]]


## 1.3) outer()

- vypocet vonkajsieho sucinu 2 poli, ktory je sucinom vsetkych moznych parov prvkov

In [ ]:
import numpy as np

arr1 = np.array([1, 3, 5])
arr2 = np.array([2, 4, 6])

# outer() to perform outer multiplication
result = np.outer(arr1, arr2)

print(result)
# output calc
# 1*2   1*4    1*6
# 3*2   3*4    3*6
# 5*2   5*4    5*6

[[ 2  4  6]
 [ 6 12 18]
 [10 20 30]]


# 1.4) linalg.det()

- vypocet determinantu matice

In [7]:
import numpy as np

# define a square matrix
arr = np.array([[1, 3], [5, 7]])

# compute the determinant of array
result = np.linalg.det(arr)
print(result)

-7.999999999999998


## 1.5) linalg.solve()

- na riesenie systemu linearnych rovnic
- pr. matica `A` a vektor `b`, riesenim je vektor `x`, ktory splna `A.x = b`

In [ ]:
import numpy as np

# define the coefficient matrix A
A = np.array([[2, 4], [6, 8]])

# define the constant vector b
b = np.array([5, 6])

# solve the system of linear equations Ax = b
x = np.linalg.solve(A, b)

print(x)
#  x = solution to the system of linear equations
#  2x + 4y = 5 and 6x + 8y = 6

[-2.    2.25]


## 1.6) linalg.inv()

- inverzia stvorcovej matice

In [ ]:
import numpy as np

# define a 2x2 matrix
arr = np.array([[2, 4], [6, 8]])
print("Array:\n", arr)

# compute the inverse of the matrix
result = np.linalg.inv(arr)

print("Inverted matrix:\n", result)

Array:
 [[2 4]
 [6 8]]
Inverted matrix:
 [[-1.    0.5 ]
 [ 0.75 -0.25]]


## 1.7) trace()

- vypocet suctu diagonalnych prvkov matice

In [ ]:
import numpy as np

# define a 3x3 matrix
arr = np.array([[6, 3, 5], [9, 2, 1], [7, 8, 4]])
print("Array:\n", arr)

# compute the trace of the matrix
result = np.trace(arr)

print("Trace of matrix:", result)
# output calc
# 6+2+4 = 12

Array:
 [[6 3 5]
 [9 2 1]
 [7 8 4]]
Trace of matrix: 12
